import { X, ExternalLink, BarChart2, Layers } from 'lucide-react'
import { useState } from 'react'
import Badge from '@/components/shared/Badge'
import VariantPerformance from './VariantPerformance'
import SegmentBreakdown from './SegmentBreakdown'
import AiInsightBox from '@/components/shared/AiInsightBox'
import { useExperimentAnalytics, useAISynthesize } from '@/api/hooks/useExperiments'
import type { Experiment } from '@/types'

interface Props {
  experiment: Experiment
  onClose: () => void
}

type DetailTab = 'variants' | 'segments'

export default function ExperimentDetail({ experiment, onClose }: Props) {
  const { data: analytics, isLoading } = useExperimentAnalytics(experiment.id)
  const { mutate: synthesize, isPending: aiLoading } = useAISynthesize()
  const [tab, setTab] = useState<DetailTab>('variants')

  return (
    <div className="bg-white rounded-xl border border-gray-200 shadow-card overflow-hidden">
      {/* Header */}
      <div className="flex items-start justify-between px-5 py-4 border-b border-gray-100">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <Badge status={experiment.status} />
            <span className="text-xs text-gray-400">{experiment.goal_metric}</span>
          </div>
          <h2 className="text-base font-semibold text-gray-900">{experiment.name}</h2>
          <a
            href={experiment.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-blue-600 hover:underline flex items-center gap-1 mt-0.5"
            onClick={(e) => e.stopPropagation()}
          >
            {experiment.url} <ExternalLink className="w-3 h-3" />
          </a>
        </div>
        <button
          onClick={onClose}
          className="p-1.5 rounded-md text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors ml-3"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Hypothesis */}
      {experiment.hypothesis && (
        <div className="px-5 py-3 bg-blue-50/40 border-b border-gray-100">
          <div className="text-xs font-medium text-blue-700 mb-0.5">Hypothesis</div>
          <p className="text-xs text-blue-600 leading-relaxed">{experiment.hypothesis}</p>
        </div>
      )}

      {/* Sub-tabs */}
      <div className="px-5 pt-4 flex gap-4 border-b border-gray-100">
        {([['variants', BarChart2, 'Variant performance'], ['segments', Layers, 'Segment breakdown']] as const).map(
          ([id, Icon, label]) => (
            <button
              key={id}
              onClick={() => setTab(id)}
              className={`flex items-center gap-1.5 pb-3 text-xs font-medium border-b-2 transition-colors ${
                tab === id
                  ? 'text-blue-700 border-blue-600'
                  : 'text-gray-500 border-transparent hover:text-gray-700'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              {label}
            </button>
          )
        )}
      </div>

      <div className="p-5">
        {isLoading ? (
          <div className="h-32 flex items-center justify-center text-sm text-gray-400">
            <div className="w-4 h-4 border-2 border-blue-200 border-t-blue-500 rounded-full animate-spin mr-2" />
            Loading analytics…
          </div>
        ) : analytics ? (
          <>
            {tab === 'variants' && <VariantPerformance analytics={analytics} />}
            {tab === 'segments' && <SegmentBreakdown analytics={analytics} />}
          </>
        ) : (
          <div className="text-sm text-gray-400 py-8 text-center">No data yet — start the experiment to collect sessions.</div>
        )}
      </div>

      {/* AI Verdict */}
      {experiment.ai_verdict ? (
        <div className="px-5 pb-5">
          <AiInsightBox
            color="blue"
            title="AI verdict"
            body={experiment.ai_verdict.verdict_summary}
            ctaLabel="See next-test backlog"
            onCta={() => {}}
          />
          {experiment.ai_verdict.next_tests?.length > 0 && (
            <div className="mt-3 space-y-1.5">
              <div className="text-xs font-medium text-gray-600">Next test ideas</div>
              {experiment.ai_verdict.next_tests.map((t, i) => (
                <div key={i} className="text-xs text-gray-600 flex gap-2">
                  <span className="text-blue-400 font-medium shrink-0">{i + 1}.</span>
                  {t}
                </div>
              ))}
            </div>
          )}
        </div>
      ) : (
        <div className="px-5 pb-5">
          <AiInsightBox
            color="blue"
            title="Generate AI analysis"
            body="Get a data-driven hypothesis verdict, key segment insights, and a next-test backlog generated by AI."
            ctaLabel="Run AI synthesis"
            onCta={() => synthesize(experiment.id)}
            loading={aiLoading}
          />
        </div>
      )}
    </div>
  )
}
